# Generated by Django 3.1.7 on 2021-03-20 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210320_0108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(default='Cairo', max_length=50),
        ),
    ]
