# Generated by Django 3.1.7 on 2021-03-18 19:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0007_auto_20210318_1835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applyforjob',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job.job'),
        ),
    ]
